name: Modrith release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish on modrinth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Make zip
        run: python tools/make_zip.py -v $GITHUB_REF_NAME
      - name: Send to modrinth
        run: python tools/publish_release.py
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
